paths:
  datapath: dataset/LEVIR-CD-256
  logpath: dataset/results/LEVIR-CD
params:
  epochs: 100
  epoch_loss: 0.0
  batch_size: 1
  lr: 0.0005
  weight_decay: 0.01
  time_interval: 1
  patience_limit: 5
settings:
  set_seed: True
