paths:
  datapath: dataset/LEVIR-CD-256
  logpath: dataset/results/LEVIR-CD
params:
  epochs: 100
  epoch_loss: 0.0
  batch_size: 1
  lr: 0.0005
  weight_decay: 0.01
  time_interval: 1
  patience_limit: 5
loss:
  seg_weight: 0.95
  cd_weight: 0.05
settings:
  set_seed: True
data_config:
  mean: (0.485, 0.456, 0.406, 0.485, 0.456, 0.406) #if transductive trud (0.485, 0.456, 0.406, 0.485, 0.456, 0.406, 0.485, 0.456, 0.406)
  std: (0.229, 0.224, 0.225, 0.229, 0.224, 0.225)
  patch_size: 256
  resize_scale: 4
  transductive: False,
  train_img_shape: (1024,1024)
  val_img_shape: (1024,1024)
  overlap_size: 128
